#!/bin/sh

/home/linuxbrew/.linuxbrew/bin/hyperfine --warmup 3 --runs 10 --export-json ./benchmarks/_benchmark_balanced_satisfy.json \
  'minizinc.exe invaders.mzn balanced1.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn balanced2.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn balanced3.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn balanced4.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn balanced5.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn balanced6.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn balanced7.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn balanced8.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn balanced9.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn balanced10.mzn --time-limit 300000'

/home/linuxbrew/.linuxbrew/bin/hyperfine --warmup 3 --runs 10 --export-json ./benchmarks/_benchmark_balanced_chuffed.json \
  'minizinc.exe invaders.mzn balanced1.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn balanced2.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn balanced3.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn balanced4.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn balanced5.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn balanced6.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn balanced7.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn balanced8.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn balanced9.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn balanced10.mzn --time-limit 300000--solver org.chuffed.chuffed'
