#!/bin/sh

/home/linuxbrew/.linuxbrew/bin/hyperfine --warmup 3 --runs 10 --export-json ./benchmarks/_generated_benchmark_satisfy.json \
  'minizinc.exe invaders.mzn aliens1.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn aliens2.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn aliens3.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn aliens4.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn aliens5.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn aliens6.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn aliens7.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn aliens8.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn aliens9.mzn --time-limit 300000' \
  'minizinc.exe invaders.mzn aliens10.mzn --time-limit 300000'

/home/linuxbrew/.linuxbrew/bin/hyperfine --warmup 3 --runs 10 --export-json ./benchmarks/_generated_benchmark_chuffed.json \
  'minizinc.exe invaders.mzn aliens1.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn aliens2.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn aliens3.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn aliens4.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn aliens5.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn aliens6.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn aliens7.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn aliens8.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn aliens9.mzn --time-limit 300000 --solver org.chuffed.chuffed' \
  'minizinc.exe invaders.mzn aliens10.mzn --time-limit 300000--solver org.chuffed.chuffed'
