#!/bin/sh

grep --color=none at\( ../clingo/aliens1.lp | bun convert.ts > aliens1.mzn
grep --color=none at\( ../clingo/aliens2.lp | bun convert.ts > aliens2.mzn
grep --color=none at\( ../clingo/aliens3.lp | bun convert.ts > aliens3.mzn
grep --color=none at\( ../clingo/aliens4.lp | bun convert.ts > aliens4.mzn
grep --color=none at\( ../clingo/aliens5.lp | bun convert.ts > aliens5.mzn
grep --color=none at\( ../clingo/aliens6.lp | bun convert.ts > aliens6.mzn
grep --color=none at\( ../clingo/aliens7.lp | bun convert.ts > aliens7.mzn
grep --color=none at\( ../clingo/aliens8.lp | bun convert.ts > aliens8.mzn
grep --color=none at\( ../clingo/aliens9.lp | bun convert.ts > aliens9.mzn
grep --color=none at\( ../clingo/aliens10.lp | bun convert.ts > aliens10.mzn
